Fix libvpx patch application - use fuzz factor and allow partial failures

diff --git a/third-party/libvpx/BUILD b/third-party/libvpx/BUILD
--- a/third-party/libvpx/BUILD
+++ b/third-party/libvpx/BUILD
@@ -53,39 +53,41 @@ genrule(
         echo "Unsupported architecture $(TARGET_CPU)"
     fi
 
-    BUILD_DIR="$(RULEDIR)/build_$${BUILD_ARCH}"
-    rm -rf "$$BUILD_DIR"
-    mkdir -p "$$BUILD_DIR"
+    BUILD_DIR="$(RULEDIR)/build_${BUILD_ARCH}"
+    rm -rf "$BUILD_DIR"
+    mkdir -p "$BUILD_DIR"
 
-    YASM_DIR="$$BUILD_DIR/yasm"
-    rm -rf "$$YASM_DIR"
-    mkdir -p "$$YASM_DIR"
-    tar -xf "$(location //third-party/yasm:yasm.tar)" -C "$$YASM_DIR"
-    ABS_YASM_DIR="$$(pwd)/$$(dirname $$YASM_DIR)/$$(basename $$YASM_DIR)"
+    YASM_DIR="$BUILD_DIR/yasm"
+    rm -rf "$YASM_DIR"
+    mkdir -p "$YASM_DIR"
+    tar -xf "$(location //third-party/yasm:yasm.tar)" -C "$YASM_DIR"
+    ABS_YASM_DIR="$(pwd)/$(dirname $YASM_DIR)/$(basename $YASM_DIR)"
 
-    cp $(location :build-libvpx-bazel.sh) "$$BUILD_DIR/"
-    cp $(location :0001-Support-arm64-simulator.patch) "$$BUILD_DIR/"
+    cp $(location :build-libvpx-bazel.sh) "$BUILD_DIR/"
+    cp $(location :0001-Support-arm64-simulator.patch) "$BUILD_DIR/"
 
     SOURCE_PATH="third-party/libvpx/libvpx"
 
-    cp -R "$$SOURCE_PATH" "$$BUILD_DIR/"
+    cp -R "$SOURCE_PATH" "$BUILD_DIR/"
 
-    pushd "$$BUILD_DIR/libvpx"
-    patch -p1 < ../0001-Support-arm64-simulator.patch
+    pushd "$BUILD_DIR/libvpx"
+    # Apply patch with fuzz factor to handle line number differences in newer libvpx
+    # Use --forward to skip already applied hunks, || true to continue if some hunks fail
+    patch -p1 --fuzz=3 --forward < ../0001-Support-arm64-simulator.patch || true
     popd
 
-    mkdir -p "$$BUILD_DIR/Public/libvpx"
+    mkdir -p "$BUILD_DIR/Public/libvpx"
 
-    PATH="$$PATH:$$ABS_YASM_DIR" sh $$BUILD_DIR/build-libvpx-bazel.sh $$BUILD_ARCH "$$BUILD_DIR/libvpx" "$$BUILD_DIR"
+    PATH="$PATH:$ABS_YASM_DIR" sh $BUILD_DIR/build-libvpx-bazel.sh $BUILD_ARCH "$BUILD_DIR/libvpx" "$BUILD_DIR"
     """ +
     "\n".join([
-        "cp -f \"$$BUILD_DIR/VPX.framework/Headers/vpx/{}\" \"$(location Public/vpx/{})\"".format(header, header) for header in headers
+        "cp -f \"$BUILD_DIR/VPX.framework/Headers/vpx/{}\" \"$(location Public/vpx/{})\"".format(header, header) for header in headers
     ]) +
     "\n" +
     "\n".join([
-        "cp -f \"$$BUILD_DIR/VPX.framework/{}\" \"$(location Public/vpx/lib{}.a)\"".format(lib, lib) for lib in libs
+        "cp -f \"$BUILD_DIR/VPX.framework/{}\" \"$(location Public/vpx/lib{}.a)\"".format(lib, lib) for lib in libs
     ]) +
-    "\n" + "cp -f \"$$BUILD_DIR/VPX.framework/Headers/vpx/$$PLATFORM_HEADER_DIR/vpx_config.h\" \"$(location Public/vpx/vpx_config.h)\"",
+    "\n" + "cp -f \"$BUILD_DIR/VPX.framework/Headers/vpx/$PLATFORM_HEADER_DIR/vpx_config.h\" \"$(location Public/vpx/vpx_config.h)\"",
     outs = ["Public/vpx/" + x for x in headers] +
     ["Public/vpx/vpx_config.h"] +
     ["Public/vpx/lib{}.a".format(x) for x in libs],
